### ISSUE TITLE
Lid sensor reading is wrong

### ISSUE THREAD

**Issue by mikvaana** [ursl/tessie#25]
Hey, we installed the lid sensor on the TEC card 1 and currently, tessie sees the lid as closed at all times. I had a look in the checkLid() function and the sensor values range from -273 to -90, but the limits for lid open/closed are above and below 4100:
```
void  driveHardware::checkLid() {
  // -- keep reading from CAN bus in readAllParamsFromCANPublic() to minimize CAN errors
  double reading = fTECData[1].reg["Temp_W"].value;
  if (reading < 4100.) {
    // -- lid is locked
    fLidStatus = 1;
  } else if (reading > 4100.) {
    // -- lid is open
    fLidStatus = -1;
  } else {
    // -- lid is closed, but not locked
    // -- unreachable, should not impact program logic above
    fLidStatus = 0;
  }
}
```
I changed the limits to -170 and then it seems to work for us, since the reading seems to be temperature-like. Should the limits be changed?

**Comment by ursl** [comment]
Are you sure your lid sensor is working as expected and not squashed somewhere? The canonical readings should be 4200 for open lid and (in our labs) something like 400 for a closed lid. The exact value depends on the amount of force applied. Have you adjusted the screw on the lever lock (between the two handles) controlling the force?

What version of tessie are you running and which version of the tec Firmware are you running? You should see a printout of the tec f/w version with a reasonably recent tessie version.

In the latest tessie version (2024/10/11-01, as of this morning) there will be a log message with the sensor value when the lidstatus changes.

Do you have a second (spare) lid sensor where you could apply pressure "by hand" with the sensor just plugged into TEC 1?

**Comment by mikvaana** [comment]
Our tessie version is 2024/09/18-1 and the TEC FW version (if I read the printout correctly) is 4. I adjusted the lever lock within reasonable limits but no change; the sensor still says the lid is locked. I also tested with a spare sensor and same result. We also tried plugging the sensor to different TECs and replacing the with different valued resistors as a test, but no luck.

Printout pasted below:

2024/10/08_13:27:41.205    INFO opentessie.csv
pigpio_start() = 0
initial readout SHT85
2024/10/08_13:27:43.655    INFO load settings from FLASH
DBX canFrame::dump
341 [2] 06 04. tec = 1 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.683    INFO getSWVersion(1) reg = 6 canID = 0x301 version = 4
DBX canFrame::dump
342 [2] 06 04. tec = 2 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.707    INFO getSWVersion(2) reg = 6 canID = 0x302 version = 4
DBX canFrame::dump
343 [2] 06 04. tec = 3 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.731    INFO getSWVersion(3) reg = 6 canID = 0x303 version = 4
DBX canFrame::dump
344 [2] 06 04. tec = 4 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.755    INFO getSWVersion(4) reg = 6 canID = 0x304 version = 4
DBX canFrame::dump
345 [2] 06 04. tec = 5 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.779    INFO getSWVersion(5) reg = 6 canID = 0x305 version = 4
DBX canFrame::dump
346 [2] 06 04. tec = 6 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.803    INFO getSWVersion(6) reg = 6 canID = 0x306 version = 4
DBX canFrame::dump
347 [2] 06 04. tec = 7 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.827    INFO getSWVersion(7) reg = 6 canID = 0x307 version = 4
DBX canFrame::dump
348 [2] 06 04. tec = 8 reg = 6 type = 0 val = -99/4
2024/10/08_13:27:43.851    INFO getSWVersion(8) reg = 6 canID = 0x308 version = 4
MainWindow w() call
2024/10/08_13:27:44.240    INFO tessie version 2024/09/18-01
2024/10/08_13:27:44.299    INFO start tessie
MainWindow w.show() call
driveHardware::doRun() entered
driveHardware::doRun() start loop
ioServer::doRun() entered, instantiate tMosq
>> tMosq - connected with server
>> subscribing to "ctrlTessie"
>> subscribed to "ctrlTessie"
ioServer::startServer()
>> tMosq - connected with server
>> subscribing to "monTessie"
>> subscribed to "monTessie"
MainWindow w.show() done
2024/10/08_13:27:45.785    INFO Free Space : 23
2024/10/08_13:27:45.786    INFO getCurrentRSS() = 85254144
2024/10/08_13:27:45.790    INFO toggleFRAS(fan)
2024/10/08_13:27:46.791    INFO Changed Interlock to HIGH
2024/10/08_13:27:46.791    INFO lid locked
2024/10/08_13:27:46.791    INFO Free Space : 23
2024/10/08_13:27:46.792    INFO getCurrentRSS() = 85581824
ioServer::doRun> Qt emit sendFromServer(Changed Interlock to HIGH)
ioServer::doRun> Qt emit sendFromServer(lid locked)
2024/10/08_13:29:51.363    INFO periodic hard reset of SHT85
2024/10/08_13:31:59.827    INFO periodic hard reset of SHT85
2024/10/08_13:34:06.355    INFO periodic hard reset of SHT85
2024/10/08_13:36:14.839    INFO periodic hard reset of SHT85
2024/10/08_13:36:36.185    INFO MainWindow::btnINTL() clicked
2024/10/08_13:36:37.186    INFO Changed Interlock to HIGH
ioServer::doRun> Qt emit sendFromServer(Changed Interlock to HIGH)
MainWindow::signalQuitProgram(), cnt = 0

**Comment by ursl** [comment]
Can you please update the TEC f/w to a recent on? E.g. https://github.com/ursl/tessie/blob/master/tecFirmware/srec/tecware-v06.srec

Please see section 4.2 of the user guide. You might need to install 
```
sudo apt-get install -y cmake libusb-1.0
```
beforehand (or so, but the error messages will tell you when building `tecFirmware/Source/LibOpenBLT` and `BootCommander`). 

There likely are changes relevant to the lid sensor (but Noah is currently not around).

**Comment by ursl** [comment]
One other comment: The lid sensor *must* be connected to TEC 1. There are a few magic slots (1, 8) that must be followed.

**Comment by ursl** [comment]
In our labs  we have two coldboxes, one had a lidsensor with the same issue as yours and one working. The non-working lidsensor had a resistance of ab out 230 Ohm (modulo possibly a "kilo" prefix that I missed). I measured the working lidsensor to have an "infinite" resistance. 

After messing around a while with the non-working sensor, it started to have an "open" resistance of 23MOhm (which is according to the [specs](https://cdn2.hubspot.net/hubfs/3899023/Interlinkelectronics%20November2017/Docs/Datasheet_FSR.pdf) and started to "work" again. However, it seems to be somewhat flaky now. 

My next proposal is to measure the open resistance of the lidsensor (unplug it from the TEC) and verify that it is according to specs. 

Attached please find photos of working and non-working sensors. 


![241011-working](https://github.com/user-attachments/assets/a81f712c-437a-4a3b-b961-170cd1eb0faf)
![241011-nonworking](https://github.com/user-attachments/assets/41356772-e8eb-4e54-9f89-a94419263b46)

**Comment by mikvaana** [comment]
Updating the TEC firmware fixed the issue (who would've thought...), thank you for the help!
