### ISSUE TITLE
Lid opened led status change

### ISSUE THREAD

**Issue by tecnovel** [ursl/tessie#31]
I would propose following changes:
If the lid is open, the green led flashes (signal tower)
If the lid is closed, green led is stable

Now the orange led goes on and the red flashes, indicating an error but there is no, what could lead to missintepretation. But the problem is, only the green error is also not the perfect idea, because the interlock is activated then(no lv and no hv). So i'm open for other opinions, but i was confused the last time i opened the box...

**Comment by ursl** [comment]
This should be solved by 0d2d01b7c6f0cfdf1ad246563fc19a495ea6ce08
