### ISSUE TITLE
Environmental status

### ISSUE THREAD

**Issue by Matas003** [ursl/tessie#32]
Should be documented somewhere that too low humidity could potentially damage SHT85 sensor. Tessie documentation(main.pdf, 10-25) page 25, "Envionmental status" it says "The ”Rel. Hum.” field shows the air relative humidity in
percent. It will turn green for values < 5%." Why it turn green if it damages our sensor? Maybe it should turn green at 10%?

**Comment by ursl** [comment]
The SHT85 will be replaced relatively soon (in November 2024), but that will take time to propagate to all coldboxes. 

I have changed the coloring scheme already in the web ui (yesterday), will do so also in MainWindow today.

**Comment by ursl** [comment]
In fact, I think I changed that already in bb30770214d607b8bf1d42228a17c2da67371570. 

So I would suggest you update to the HEAD of the master branch.

**Comment by ursl** [comment]
FWIW: See https://github.com/ursl/tessie/issues/29#issuecomment-2434795740
