### ISSUE TITLE
VProbe readout

### ISSUE THREAD

**Issue by ursl** [ursl/tessie#4]
NP will attach documentation

**Comment by tecnovel** [comment]
[vprobe_V2.pdf](https://github.com/ursl/tessie/files/12927234/vprobe_V2.pdf)

Here is the documentation, where you can see how you read the voltages

**Comment by ursl** [comment]
Simply publish the results. NP is not very interested in this.

**Comment by clelange** [comment]
So either we get the values in mV, which I would prefer as done in https://gitlab.cern.ch/psi/moduleprobe/-/blob/v2.2.1/read_voltages.py?ref_type=tags#L49-L58 or tessie provides the plain pin values. It would be great if all values were returned as a JSON blob or in some other structured way, but all together (and not requesting them one by one).
All those values would then be per module slot, i.e. eight times.

All details on the mapping are in the file linked above and I2C details in https://gitlab.cern.ch/psi/moduleprobe/-/blob/v2.2.1/vprobe.py

**Comment by ursl** [comment]
8c28a82d6802e7463bad5ef07f648e6a092dc9a0 addresses most of this

**Comment by ursl** [comment]
8b1c52557fa75b1faec8b4c8062bde6b6eaf3793 adds order into the readout. Needs to be checked.

**Comment by ursl** [comment]
b782cba4d298d5c8fc555c765468f0b951edec75 does it.
