### ISSUE TITLE
Adding support for the new PiHat: Interlock pin and lamp tower

### ISSUE THREAD

**Issue by tecnovel** [ursl/tessie#9]
On GPIO 23 there is now a HV Interlock. If this pin is logic low, the Interlock is activated.
Then we have a signal Lamp Tower.
GPIO 17,27,22 (Red, Yellow, Green) logic High = activated

**Comment by ursl** [comment]
Finish this on 2023/11/09

**Comment by ursl** [comment]
We should discuss the logic. (Low = OK and High = interlock broken?) Apart from this, 2518688e20a246cb194be6b9738fcc398462d36b implements this.

**Comment by ursl** [comment]
Completed with ff80ad1
